#
# User-defined substitutions:
#   _CLOUDSDK_COMPUTE_ZONE
#   _CLOUDSDK_CONTAINER_CLUSTER
#   _GITHUB_USERNAME
#   _KMS_KEY 
#   _KMS_KEYRING
#

steps:
  # Build the trends container image.
  - name: 'gcr.io/cloud-builders/docker'
    env:
      - 'SHUTTER_TOKEN=${_SHUTTER_TOKEN}'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/trends:${COMMIT_SHA}'
      - '.'

  # Retrieve and decrypt the GitHub Hub configuration. 
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        gsutil cp gs://${PROJECT_ID}-trends-configs/hub.enc hub.enc

        gcloud kms decrypt \
          --ciphertext-file hub.enc \
          --plaintext-file /config/hub \
          --location global \
          --keyring ${_KMS_KEYRING} \
          --key ${_KMS_KEY}
    volumes:
      - name: 'config'
        path: /config

  # Generate a kubeconfig file for the given GKE cluster.
  - name: 'gcr.io/cloud-builders/kubectl'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
      - 'KUBECONFIG=/kube/config'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        CLUSTER=$$(gcloud config get-value container/cluster)
        PROJECT=$$(gcloud config get-value core/project)
        ZONE=$$(gcloud config get-value compute/zone)

        gcloud container clusters get-credentials "$${CLUSTER}" \
          --project "$${PROJECT}" \
          --zone "$${ZONE}"
    volumes:
      - name: 'kube'
        path: /kube

  # Clone the trends-infrastructure-staging repo.
  - name: 'gcr.io/hightowerlabs/hub'
    env:
      - 'HUB_CONFIG=/config/hub'
      - 'KUBECONFIG=/kube/config'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        ACTIVE_ACCOUNT=$(gcloud auth list --filter=status:ACTIVE --format="value(account)")

        hub config --global credential.https://github.com.helper /usr/local/bin/hub-credential-helper 
        hub config --global hub.protocol https
        hub config --global user.email "$${ACTIVE_ACCOUNT}"
        hub config --global user.name "Google Container Builder"

        hub clone "${_GITHUB_USERNAME}/trends-infrastructure-staging"

        cp docker-compose.yaml trends-infrastructure-staging

        cd trends-infrastructure-staging

        sed -i "s%gcr.io/${PROJECT_ID}/trends.*%gcr.io/${PROJECT_ID}/trends:${COMMIT_SHA}%g" docker-compose.yaml
        sed -i "/#/s/#//g" docker-compose.yaml
        sed -i "/build.*/s/^/#/g" docker-compose.yaml

        hub add docker-compose.yaml

        hub commit -F- <<EOF
        Update the trends application

        This commit updates the trends deployment container image to:

            gcr.io/${PROJECT_ID}/trends:${COMMIT_SHA}.

        Build ID: ${BUILD_ID}
        EOF

        hub push origin master
    volumes:
      - name: 'config'
        path: /config
      - name: 'kube'
        path: /kube

images:
  - 'gcr.io/${PROJECT_ID}/trends:${COMMIT_SHA}'
