steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/trends:${COMMIT_SHA}', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/trends:${COMMIT_SHA}']
  # - name: 'gcr.io/cloud-builders/kubectl'
  #   args: ['set', 'image', 'deployment/web', 'web=gcr.io/${PROJECT_ID}/trends:${COMMIT_SHA}']
  #   env:
  #     - 'CLOUDSDK_COMPUTE_ZONE=europe-west4-c'
  #     - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
  # - name: 'gcr.io/cloud-builders/kubectl'
  #   args: ['set', 'image', 'deployment/worker', 'worker=gcr.io/${PROJECT_ID}/trends:${COMMIT_SHA}']
  #   env:
  #     - 'CLOUDSDK_COMPUTE_ZONE=europe-west4-c'
  #     - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'

  # Generate a kubeconfig file for the given GKE cluster.
  - name: 'gcr.io/cloud-builders/kubectl'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
      - 'KUBECONFIG=/kube/config'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        CLUSTER=$$(gcloud config get-value container/cluster)
        PROJECT=$$(gcloud config get-value core/project)
        ZONE=$$(gcloud config get-value compute/zone)

        gcloud container clusters get-credentials "$${CLUSTER}" \
          --project "$${PROJECT}" \
          --zone "$${ZONE}"
    volumes:
      - name: 'kube'
        path: /kube
