steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/trends:${COMMIT_SHA}', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/trends:${COMMIT_SHA}']
  # - name: 'gcr.io/cloud-builders/kubectl'
  #   args: ['set', 'image', 'deployment/my-deployment', 'my-container=gcr.io/${PROJECT_ID}/trends:${COMMIT_SHA}']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=europe-west4-c'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'