version: '3'

services:
    rabbit:
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=user
            - RABBITMQ_DEFAULT_PASS=pass
        ports:
            - "5673:5672"

    worker:
        build:
            context: .
        volumes:
            - .:/app
        depends_on:
            - rabbit
