version: '3'

services:
    rabbit:
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=user
            - RABBITMQ_DEFAULT_PASS=pass
        ports:
            - "5672:5672"

    worker:
        build: .
        command: celery -A trends worker
        volumes:
            - ~/.ipython:/root/.ipython
            - .:/app
        environment:
            - TOKEN_SHUTTERSTOCK=${TOKEN_SHUTTERSTOCK}
        depends_on:
            - rabbit

    web:
        build: .
        volumes:
            - ~/.ipython:/root/.ipython
            - .:/app
        command: celery -A trends flower --port=80
        ports:
            - "80:80"
        depends_on:
            - worker
        environment:
            - GET_HOSTS_FROM=dns
            - TOKEN_SHUTTERSTOCK=${TOKEN_SHUTTERSTOCK}
        labels:
            kompose.service.type: LoadBalancer
