version: '3'

services:
    rabbit:
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=user
            - RABBITMQ_DEFAULT_PASS=pass
        ports:
            - "5672:5672"

    worker:
        build: .
        image: gcr.io/trends-217607/trends:1
        command: celery -A trends worker
        depends_on:
            - rabbit

    flower:
        build: .
        image: gcr.io/trends-217607/trends:1
        command: celery -A trends flower
        ports:
            - "80:5555"
        depends_on:
            - worker
